 
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            echo $NIX_PATH
            echo $PATH
      - run:
          name: Tests
          command: |
            echo $NIX_PATH
            echo $PATH
