 
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl -L https://nixos.org/nix/install | sh
            echo "source /home/circleci/.nix-profile/etc/profile.d/nix.sh" >> $BASH_ENV
            
      - run:
          name: Tests
          command: |
            echo $NIX_PATH
            echo $PATH
            nix-env -iA pkgs.silver-searcher -f default.nix
